using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MediatR;
using EMR.Application.DTOs;
using System.ComponentModel.DataAnnotations;

namespace EMR.API.Controllers;

[ApiController]
[Route("api/v1/[controller]")]
[Authorize]
[Produces("application/json")]
public class EncountersController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly ILogger<EncountersController> _logger;

    public EncountersController(IMediator mediator, ILogger<EncountersController> logger)
    {
        _mediator = mediator;
        _logger = logger;
    }

    /// <summary>
    /// Get all encounters with filtering
    /// </summary>
    /// <param name="patientId">Filter by patient ID</param>
    /// <param name="providerId">Filter by provider ID</param>
    /// <param name="startDate">Filter by start date</param>
    /// <param name="endDate">Filter by end date</param>
    /// <param name="status">Filter by status</param>
    /// <param name="page">Page number (default: 1)</param>
    /// <param name="pageSize">Page size (default: 20)</param>
    /// <returns>List of encounters</returns>
    [HttpGet]
    [ProducesResponseType(typeof(IEnumerable<EncounterDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> GetEncounters(
        [FromQuery] long? patientId = null,
        [FromQuery] long? providerId = null,
        [FromQuery] DateTime? startDate = null,
        [FromQuery] DateTime? endDate = null,
        [FromQuery] string? status = null,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 20)
    {
        try
        {
            _logger.LogInformation("Getting encounters - PatientId: {PatientId}, ProviderId: {ProviderId}, Status: {Status}",
                patientId, providerId, status);

            // This would use GetEncountersQuery
            return Ok(new List<EncounterDto>());
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting encounters");
            return StatusCode(500, new { message = "An internal error occurred" });
        }
    }

    /// <summary>
    /// Get encounter by ID
    /// </summary>
    /// <param name="id">Encounter ID</param>
    /// <returns>Encounter details</returns>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(EncounterDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> GetEncounter(long id)
    {
        try
        {
            _logger.LogInformation("Getting encounter with ID: {EncounterId}", id);

            // This would use GetEncounterByIdQuery
            return NotFound(new { message = "Encounter not found" });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting encounter {EncounterId}", id);
            return StatusCode(500, new { message = "An internal error occurred" });
        }
    }

    /// <summary>
    /// Create a new encounter
    /// </summary>
    /// <param name="request">Encounter creation details</param>
    /// <returns>Created encounter</returns>
    [HttpPost]
    [ProducesResponseType(typeof(EncounterDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> CreateEncounter([FromBody] CreateEncounterRequest request)
    {
        try
        {
            _logger.LogInformation("Creating encounter for patient {PatientId} with provider {ProviderId}",
                request.PatientId, request.ProviderId);

            // This would use CreateEncounterCommand
            var encounter = new EncounterDto
            {
                Id = 1, // This would be generated by the database
                PatientId = request.PatientId,
                ProviderId = request.ProviderId,
                EncounterType = request.EncounterType,
                ChiefComplaint = request.ChiefComplaint,
                Status = "in-progress",
                EncounterDateTime = request.EncounterDateTime,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };

            return CreatedAtAction(nameof(GetEncounter), new { id = encounter.Id }, encounter);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating encounter");
            return StatusCode(500, new { message = "An internal error occurred" });
        }
    }

    /// <summary>
    /// Update an encounter
    /// </summary>
    /// <param name="id">Encounter ID</param>
    /// <param name="request">Encounter update details</param>
    /// <returns>Updated encounter</returns>
    [HttpPut("{id}")]
    [ProducesResponseType(typeof(EncounterDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> UpdateEncounter(long id, [FromBody] UpdateEncounterRequest request)
    {
        try
        {
            _logger.LogInformation("Updating encounter {EncounterId}", id);

            // This would use UpdateEncounterCommand
            return NotFound(new { message = "Encounter not found" });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error updating encounter {EncounterId}", id);
            return StatusCode(500, new { message = "An internal error occurred" });
        }
    }

    /// <summary>
    /// Complete an encounter
    /// </summary>
    /// <param name="id">Encounter ID</param>
    /// <param name="request">Encounter completion details</param>
    /// <returns>Completed encounter</returns>
    [HttpPost("{id}/complete")]
    [ProducesResponseType(typeof(EncounterDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> CompleteEncounter(long id, [FromBody] CompleteEncounterRequest request)
    {
        try
        {
            _logger.LogInformation("Completing encounter {EncounterId}", id);

            // This would use CompleteEncounterCommand
            return NotFound(new { message = "Encounter not found" });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error completing encounter {EncounterId}", id);
            return StatusCode(500, new { message = "An internal error occurred" });
        }
    }

    /// <summary>
    /// Get encounter notes
    /// </summary>
    /// <param name="id">Encounter ID</param>
    /// <returns>Encounter notes</returns>
    [HttpGet("{id}/notes")]
    [ProducesResponseType(typeof(IEnumerable<EncounterNote>), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> GetEncounterNotes(long id)
    {
        try
        {
            _logger.LogInformation("Getting notes for encounter {EncounterId}", id);

            return Ok(new List<EncounterNote>());
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting notes for encounter {EncounterId}", id);
            return StatusCode(500, new { message = "An internal error occurred" });
        }
    }

    /// <summary>
    /// Add note to encounter
    /// </summary>
    /// <param name="id">Encounter ID</param>
    /// <param name="request">Note details</param>
    /// <returns>Created note</returns>
    [HttpPost("{id}/notes")]
    [ProducesResponseType(typeof(EncounterNote), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> AddEncounterNote(long id, [FromBody] AddEncounterNoteRequest request)
    {
        try
        {
            _logger.LogInformation("Adding note to encounter {EncounterId}", id);

            var note = new EncounterNote
            {
                Id = 1,
                EncounterId = id,
                Content = request.Content,
                NoteType = request.NoteType,
                CreatedAt = DateTime.UtcNow
            };

            return CreatedAtAction(nameof(GetEncounterNotes), new { id }, note);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error adding note to encounter {EncounterId}", id);
            return StatusCode(500, new { message = "An internal error occurred" });
        }
    }
}

// Request DTOs
public class CreateEncounterRequest
{
    [Required]
    public long PatientId { get; set; }

    [Required]
    public long ProviderId { get; set; }

    [Required]
    public string EncounterType { get; set; } = string.Empty;

    public string? ChiefComplaint { get; set; }

    [Required]
    public DateTime EncounterDateTime { get; set; }

    public long? AppointmentId { get; set; }
}

public class UpdateEncounterRequest
{
    public string? EncounterType { get; set; }
    public string? ChiefComplaint { get; set; }
    public string? AssessmentAndPlan { get; set; }
    public string? Status { get; set; }
    public DateTime? EncounterDateTime { get; set; }
}

public class CompleteEncounterRequest
{
    [Required]
    public string AssessmentAndPlan { get; set; } = string.Empty;
    
    public string? Diagnosis { get; set; }
    public string? TreatmentPlan { get; set; }
    public string? FollowUpInstructions { get; set; }
}

public class AddEncounterNoteRequest
{
    [Required]
    public string Content { get; set; } = string.Empty;

    [Required]
    public string NoteType { get; set; } = string.Empty;
}

// Response DTOs
public class EncounterNote
{
    public long Id { get; set; }
    public long EncounterId { get; set; }
    public string Content { get; set; } = string.Empty;
    public string NoteType { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public string? CreatedBy { get; set; }
}